### PR TITLE
feat(types): add `banners` in `renderingContent`

### PR DESCRIPTION
**Pull request by aymeric-giraudet**
These are types for the upcoming no-code Banner feature.

### CODE REVIEW

**Review by taylorcjohnson — DISMISSED** [review]
Approving since the failing tests don't appear to be related.

**Review by shortcuts — DISMISSED** [review]
looks great, could you please reflect it in https://github.com/algolia/api-clients-automation/blob/b621988bce6f17f53bc12cc04d2f852d79b3cfee/specs/common/schemas/IndexSettings.yml#L983?

for the CI, it's super flaky so... you'll have to re-run it a bunch of times :(

**Comment by aymeric-giraudet** [comment]
@shortcuts doesn't the Swagger spec file get generated itself too ?
If not we may do it manually but it should be done by those owning the backend code

**Comment by shortcuts** [comment]
> @shortcuts doesn't the Swagger spec file get generated itself too ? If not we may do it manually but it should be done by those owning the backend code

no the spec is the entrypoint that generates everything

**Review by shortcuts — APPROVED** [review]

**Pull request merged**
