### PR TITLE
ci(circle): set up basic config

### PR DESCRIPTION
**Pull request by Haroenv**
- [x] unit tests
- [x] lint
- [x] build size
- [ ] integration test (node) → two mysterious failures
- [ ] integration tests (browser) → hostname not set correctly?
- [ ] unit tests (browser) → hostname?
- [x] unit test (node)

### CODE REVIEW

**Comment by Haroenv** [comment]
I think https://discuss.circleci.com/t/missing-sauce-script-error-when-trying-to-test-with-sauce-labs/21191/3 (downloading sauce connect) might be necessary for it to work: 

```yml
- run:
    name: Start SauceLabs Tunnel (required if testing on CircleCI container)
    command: |
       curl https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz -o saucelabs.tar.gz
       tar -xzf saucelabs.tar.gz
       cd sc-*
       # startup saucelabs tunnel as background task (its a blocking command)
       bin/sc -u ${SAUCELABS_USER} -k ${SAUCELABS_KEY} &
       #wait for sauce tunnel up to 1 minute
       wget --retry-connrefused --no-check-certificate -T 60 localhost:4445
```

**Comment by Haroenv** [comment]
Idea: leave travis for the integration tests, circle for unit test, migrate later?

**Comment by Haroenv** [comment]
I'll let you reimplement this on v4 @nunomaduro & @sarahdayan

**Comment by nunomaduro** [comment]
@Haroenv Thanks for closing this, we will handle this.

**Pull request closed without merging**
