### PR TITLE
feat(types): add hide in renderingContent facet values

### PR DESCRIPTION
**Pull request by thomasbritton**
Adds typing for the new `hide` property in renderingContent facet values

JIRA ticket: https://algolia.atlassian.net/browse/EMERCH-1518

### CODE REVIEW

**Comment by thomasbritton** [comment]
The failing tests seem unrelated, are they flakey?

**Review by aymeric-giraudet — APPROVED** [review]
Looks good ! And yes the tests are flakey @thomasbritton, gotta rerun them :/

**Comment by thomasbritton** [comment]
> Looks good ! And yes the tests are flakey @thomasbritton, gotta rerun them :/

I have re-run 5 times not passing still

**Comment by shortcuts** [comment]
hey @thomasbritton yes it fails aaaa looooot (can't wait to move to https://github.com/algolia/api-clients-automation), it might not be flakiness at this point, I think something is broken, i'll try to fix it on monday

**Comment by thomasbritton** [comment]
> hey @thomasbritton yes it fails aaaa looooot (can't wait to move to https://github.com/algolia/api-clients-automation), it might not be flakiness at this point, I think something is broken, i'll try to fix it on monday

Hey @shortcuts , I'm trying it once more for luck! But thank you for your support on this.

**Comment by thomasbritton** [comment]
Hey @shortcuts , just wondering if you have been able to have a look at this yet?

**Comment by shortcuts** [comment]
trying right now

**Pull request merged**
