### PR TITLE
fix(forwardToReplicas): use and allow forwardToReplicas instead of forwardToSlaves

### LINKED ISSUE #395: forwardToReplicas should be used instead of forwardToSlaves
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The current API of `saveSynonym` expect a `forwardToSlaves` parameters. In regards to our internal renaming, it should now be reflected as `forwardToReplicas`. The change is already available on the REST API.

**What is the expected behavior?**
`forwardToSlaves` should be renamed to `forwardToReplicas` and the documentation should advocate for using `forwardToReplicas`. `forwardToSlaves` should still work as an alias but should display a deprecation warning.

### PR DESCRIPTION
**Pull request by vvo**
fixes #395

### CODE REVIEW

**Comment by pixelastic** [comment]
How do you feel about adding a deprecation warning for people using `forwardToSlaves`?

**Comment by vvo** [comment]
> How do you feel about adding a deprecation warning for people using forwardToSlaves?

Good idea yes

**Comment by pixelastic** [comment]
Gentle ping :ping_pong:

**Comment by vvo** [comment]
Done, will show one warning per session.

**Comment by pixelastic** [comment]
Thanks!

**Pull request merged**
