### PR TITLE
feat(security): use https by default

### PR DESCRIPTION
**Pull request by vvo**
Originally the fact to use the page protocol or http by default was made
to speed up first requests to avoid initiating an https connection.

Nowadays this is no more of a big issue performance wise (citation
needed), but security wise, the use of http by default combined with
JSONP can be a big issue of MITM attacks.

### CODE REVIEW

**Comment by Haroenv** [comment]
Releasing tomorrow

**Comment by asurak** [comment]
Is it released?

**Comment by Haroenv** [comment]
@asurak ready to release but just now had a doubt if this might not accidentally suppress the error when people run any of the methods we guard to only run on https

**Comment by Haroenv** [comment]
Never mind, was confused. That error is in the server, and that's why I didn't find it in the code base 👍

**Comment by Haroenv** [comment]
3.25.0

**Pull request merged**
