### PR TITLE
feat: remaining-validity

### LINKED ISSUE #772: New method: GetSecuredApiKeyRemainingValidity
## Summary

When a secured API keys expire, search breaks. The current workaround is more complex
than it needs to be. 

The options for developers using Algolia require, at every place where a search
operation is performed, catching an operation error, identify it as a
"ValidUntil" error, then regenerate the API key, and perform the search
operation again.

The idea is to define a method which tells if a `SecuredAPIKey`
is expired or not without making a single call to Algolia's API.

## References

- Specs: https://github.com/algolia/algoliasearch-client-specs-internal/pull/25

### PR DESCRIPTION
**Pull request by nunomaduro**
This pull request adds `getSecuredApiKeyRemainingValidity` as specified on the api client specs.

closes #772

### CODE REVIEW

**Comment by Haroenv** [comment]
Looks good, bundle size change is odd though, since angular shouldn’t have this file, maybe it’s just the error

**Comment by nunomaduro** [comment]
Waiting for https://github.com/algolia/algoliasearch-client-javascript/pull/779.

**Comment by julienbourdeau** [comment]
It seems like this is only implemented for Node, not in the browser, am I correct?

If so, why is it not available in the browser?

**Comment by nunomaduro** [comment]
Because the `generateSecuredApiKey` as also browser only. On the JavaScript on the default preset will contain this features on the browser too.

**Comment by julienbourdeau** [comment]
I understand 👍 I'm very exited for v4.
This is a very important feature, as your frontend might be using secured api key, you need to know when to ask for a new key.

**Pull request merged**
