### PR TITLE
fix(findAnswers): expose in lite version

### PR DESCRIPTION
**Pull request by eunjae-lee**
## Summary

This PR exposes `findAnswers` method in the lite version. In our documents, we kind of encourage to use `algoliasearch/lite` a lot. So we'd better have this method in the lite version as well for better adoption.

### CODE REVIEW

**Comment by Haroenv** [comment]
I didn't do this for bundlesize, but I guess it makes sense. You still need to update the size :)

**Comment by eunjae-lee** [comment]
> I didn't do this for bundlesize, but I guess it makes sense. You still need to update the size :)

It didn't exceed the current threshold :)

**Comment by Haroenv** [comment]
can you add the integration test on browser-lite now too? it's https://github.com/algolia/algoliasearch-client-javascript/blob/master/specs/answers.spec.ts (you can see https://github.com/algolia/algoliasearch-client-javascript/blob/master/specs/search.spec.ts for lite usage)

**Review by Haroenv — APPROVED** [review]
lgtm once tests pass 👍

**Pull request merged**
