### PR TITLE
chore(deprecation): deprecate waitTask --> waitForCompletion

### PR DESCRIPTION
**Pull request by Haroenv**
We renamed this one in v4 because it's not really proper English

- [x] [wiki entry](https://github.com/algolia/algoliasearch-client-javascript/wiki/Deprecated#indexwaittask)
- [x] alias in v3
- [x] v4 implementation

### CODE REVIEW

**Comment by vvo** [comment]
Where's waitForCompletion implemented?

**Comment by Haroenv** [comment]
It's not implemented yet in v3, forgot to push that

**Comment by vvo** [comment]
May need to update tests too.

Is waitForCompletion the new waitTask for all API clients?

**Comment by Haroenv** [comment]
I think it was originally @codeharmonics suggesting this change

**Comment by Haroenv** [comment]
Java has `waitForCompletion`, Scala `waitFor`, other ones have `waitTask`, `wait_task`

**Comment by rayrutjes** [comment]
I feel like we should try to keep some consistency.
If we are to rename methods like these, we should validate them with the API maintainers and implement the change everywhere?

**Comment by rayrutjes** [comment]
Java and Scala are the exceptions here if I'm not mistaken.

**Comment by redox** [comment]
I agree with @rayrutjes, not sure we want to introduce a new wording here. This method should anyway never be used for something else that testing purposes.

**Comment by codeharmonics** [comment]
@clement-leprovost started a discussion about renaming waitTask. Everybody agreed that it needed to be more explicit - wait for the task to do what???  Some suggested waitForTask, waitForTaskToComplete, or waitForCompletion.

**Comment by rayrutjes** [comment]
@codeharmonics whatever is best indeed. Some of the suggestions really are more explicit than today.
However, I think that renaming single methods like this will create a lot of noise.
Maybe we should start creating a document listing all `methods` / `concepts` etc so that we can eventually all go in the same direction when releasing major versions.

@Haroenv also has some nice ideas around `Requester` etc which are probably worth discussing / implementing in other clients in the future.

**Comment by codeharmonics** [comment]
Doc team will be revisiting our API client methods, adding exact parameters and return results, as well as more code samples. We can start creating a list of name changes. But I'm curious how we manage interface changes? Can old clients still use the existing names? Are new clients encouraged or even required to use the new names?

**Comment by Haroenv** [comment]
If this is too contentious of a name change I can keep it like it is, but I only made this PR because we discussed it on Slack and it was on my TODO

**Comment by Haroenv** [comment]
Reverting this. We will reconsider this kind of naming on a global level at a later stage

**Pull request closed without merging**
