### PR TITLE
feat(version): expose version on presets

### PR DESCRIPTION
**Pull request by Haroenv**
This is the API we have in v3, so some people might rely on this? It also makes sense to me to access it before instantiation. If you disagree, no hard feelings :)

### CODE REVIEW

**Comment by francoischalifour** [comment]
I think we should avoid mutating our exports like this. I believe bundlers consider this as a side effect. Why not export `version` the normal way?

**Comment by nunomaduro** [comment]
Context, with this pull request we allow to get the version in 3 different ways:
- 1 - module `import { version } from '@algolia/common'.
- 2 - instance `client.version`
- 3 - constructor: `algoliasearch.version`.

**Comment by francoischalifour** [comment]
@nunomaduro Then it would make sense to also be able to import it like this:

```js
import { version } from 'algoliasearch';
// and
import { version } from 'algoliasearch/lite';
```

Wydt?

**Comment by Haroenv** [comment]
>  I believe bundlers consider this as a side effect

I didn't think of that, do you have a link for that?

**Comment by nunomaduro** [comment]
@francoischalifour @Haroenv Feedback: when you put `sideEffects: false` bundlers will assume that there is no side effects at all - He will not even search for side effects. 

Second, adding a property to an object (`algoliasearch`) exported by our module could never be a side effect.

**Comment by nunomaduro** [comment]
@Haroenv I agree with @francoischalifour that we should just provide two ways of getting the version.

1. on the modular way `import { version } from '@algolia/common'.`.
2. on the preset way `import { version } from 'PRESET';`

If you agree, I can clean up this pull request, and adapt it.

**Comment by francoischalifour** [comment]
@Haroenv I think it came up when talking with @samouss. I can't find many resources on this topic. Webpack's guide on [Tree Shaking](https://webpack.js.org/guides/tree-shaking/) is interesting but doesn't talk about what is considered as a side effect.

**Pull request merged**
