### PR TITLE
build: hide yarn.lock file for better diff

### PR DESCRIPTION
**Pull request by jbpionnier**
**Summary**

https://medium.com/@clarkbw/managing-generated-files-in-github-1f1989c09dfd

**Result**

Better PR & Diff

### CODE REVIEW

**Comment by Haroenv** [comment]
Thanks for the PR, really appreciate all contributions, but as far as I saw, Yarn.lock always has been collapsed in diffs without any configuration. Did you add this because you saw it showing up in full somewhere?

**Comment by vvo** [comment]
@Haroenv It might be because you have a GitHub extension like refined GitHub? This parameter is also useful for local "git diff" commands. Still I never felt the big pain here. @jbpionnier where were you feeling the pain recently on this on Algolia JavaScript client repo?

**Comment by Haroenv** [comment]
Nope, I use GitHub without extensions :)

**Comment by Haroenv** [comment]
Thanks for your PR @jbpionnier, but we haven't seen an issue with yarn not auto-hiding. Please of course feel free to contribute in the future!

**Pull request closed without merging**
