### PR TITLE
Places API V4 proposal

### PR DESCRIPTION
**Pull request by vvo**
Little changes to the examples and actual naming around getObject getObjects => getPlace getPlaces.

### CODE REVIEW

**Comment by vvo** [comment]
I wonder if this makes sense to use getPlace and getPlaces rather than getObject. Maybe that's not so good idea because then people will not easily do the link between places and indexes when they want to mix both.

**Comment by bobylito** [comment]
> I wonder if this makes sense to use getPlace and getPlaces rather than getObject. Maybe that's not so good idea because then people will not easily do the link between places and indexes when they want to mix both.

On the other hand it clearly shows that those are different. Also getPlaces is more semantically accurate. That's a good name IMHO

**Comment by vvo** [comment]
Thx @bobylito for feedback on this :)

**Comment by Haroenv** [comment]
That's a great idea 😄

**Pull request merged**
