### PR TITLE
chore: add code sandbox ci

### PR DESCRIPTION
**Pull request by eunjae-lee**
This PR sets up CodeSandbox CI to make it easier to test the temporary library on CodeSandbox or wherever.

### CODE REVIEW

**Comment by Haroenv** [comment]
looks like it's not yet the right sandbox :)

**Comment by eunjae-lee** [comment]
yup. there's no proper example in this repo to use as a sandbox template.

I've manually got this, though.
https://codesandbox.io/s/vanilla-forked-g5lsj?file=/src/index.js

**Comment by Haroenv** [comment]
you can add an example in the playground folder

**Comment by francoischalifour** [comment]
How about using the [Create InstantSearch App sandbox for the client](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/javascript-client) and aliasing the dependency?

**Comment by eunjae-lee** [comment]
> How about using the [Create InstantSearch App sandbox for the client](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/javascript-client) and aliasing the dependency?

That's a good sandbox candidate. I'm trying it out.

**Review by francoischalifour — APPROVED** [review]

**Pull request merged**
