### PR TITLE
feat(api keys): rename all *userKey to *apiKey

### PR DESCRIPTION
**Pull request by vvo**
with backward compat and depreciation messages

### CODE REVIEW

**Comment by redox** [comment]
I'm always confused when it comes to acronyms... whether we should camelCase them or not :/ I think I would have written `listAPIKeys()` instead of `listApiKeys` but no strong opinion.

**Comment by vvo** [comment]
> I'm always confused when it comes to acronyms... whether we should camelCase them or not :/ I think I would have written listAPIKeys() instead of listApiKeys() but no strong opinion.

I would also prefer to always write api as API even in this case, so listAPIKeys(). Wonder if it's a real struggle or just another OCD.

Our chosen spec was to use listApiKeys form from what I read and see what's implemented already in other clients: https://github.com/algolia/algoliasearch-client-php/commit/c9bdad396d871fbc11022c1fa82e43d6b0333bcb

Still using API in comments.

**Comment by rayrutjes** [comment]
Same feeling @redox I think it all comes down to personal prefs and consistency in projects.
I use both notations depends on the project. Personally I prefer the Api approach, because when you need to convert to first char to lower, you end up with aPI otherwise.

**Comment by vvo** [comment]
Very common acronyms (i.e. not OUR acronyms, like applicationID, we ditched this in favour of applicationId or appId) should stay capitalized from my POV. React thinks the same: https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml

image

But at the same time, they have:

image

So is the rule:
- when acronym is in leading position: lowercase?
- when acronym is in trailing position: uppercase?

**Comment by Haroenv** [comment]
htmlFor comes from the DOM API https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/htmlFor

**Comment by vvo** [comment]
this ships on monday so we can follow the deployment

**Pull request merged**
